version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 'wsgi:app'
    volumes:
      - sqlite_data_prod:/home/app/web/instance/
    expose:
      - 5000
    env_file:
      - .env.prod

  nginx:
    build: nginx
    ports:
      - 80:80
    depends_on:
      - web


volumes:
  sqlite_data_prod:
